[package]
name = "taroc_context"
version = "0.1.0"
edition = "2024"


[dependencies]
taroc_package = { path = "../taroc_package" }
taroc_span = { path = "../taroc_span" }
taroc_diagnostics = { path = "../taroc_diagnostics" }
