[package]
name = "taroc_thir"
version = "0.1.0"
edition = "2024"

[dependencies]
taroc_sema = { path = "../taroc_sema" }
taroc_hir = { path = "../taroc_hir" }
taroc_span = { path = "../taroc_span" }
index_vec = "0.1.4"
