pub const FILE_EXTENSION: &str = "tr";
pub const SOURCE_DIRECTORY: &str = "src";
pub const ROOT_MODULE_NAME: &str = "main";
pub const MANIFEST_FILE: &str = "package.toml";
pub const LOCK_FILE: &str = "package.lock";
pub const LANGUAGE_HOME: &str = "TARO_HOME";
pub const PACKAGE_STORE: &str = "packages"; // $TARO_HOME/packages
pub const PACKAGE_SOURCE: &str = "sources"; // $TARO_HOME/sources
pub const VCS_REMOTE_NAME: &str = "origin";
