[package]
name = "taroc_hir"
version = "0.1.0"
edition = "2024"

[features]
nightly = []

[dependencies]
colored = "3.0.0"
taroc_span = { path = "../taroc_span" }
taroc_error = { path = "../taroc_error" }
taroc_ast_ir = { path = "../taroc_ast_ir" }
rustc-hash = "2.1.1"
index_vec = "0.1.4"
