#![feature(if_let_guard)]
mod adt;
mod attribute;
mod block;
mod declaration;
mod expression;
mod function;
mod generics;
mod identifier;
mod package;
mod path;
mod pattern;
mod restrictions;
mod sequence;
mod span;
mod statement;
mod ty;
mod utils;
mod visibility;
pub use package::parse_module;
pub use package::parse_package;
